### ISSUE TITLE
请问这个提示“主题没有角色”是啥，哪里配置错了吗?日志没看到有报错哦[BUG]

### ISSUE THREAD

**Issue by G291131988** [metersphere/jenkins-plugin#10]
Jenkins触发接口测试之后，提示用例全部通过，但是MS后台并没有生成报告

jenkins-plugin版本1.7.0

![image](https://user-images.githubusercontent.com/37016695/106453879-e9929f00-64c4-11eb-86e2-85b3b0a90d67.png)
![image](https://user-images.githubusercontent.com/37016695/106453894-ee575300-64c4-11eb-8e1f-4f2f68dc5355.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请更新 metersphere 及插件到 1.7.3 版本进行验证。
