### ISSUE TITLE
pipline need parameter when run generate code.

### ISSUE THREAD

**Issue by leopardxu** [metersphere/jenkins-plugin#11]
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 7: Missing required parameter: "logger" @ line 7, column 15.
                 meterSphere environmentId: 'd52aed15-4f99-42ce-8bc7-edb09b2607ea', 
                 ^

WorkflowScript: 7: Missing required parameter: "testCaseNodeId" @ line 7, column 15.
                 meterSphere environmentId: 'd52aed15-4f99-42ce-8bc7-edb09b2607ea', 
                 ^

WorkflowScript: 7: Missing required parameter: "testId" @ line 7, column 15.
                 meterSphere environmentId: 'd52aed15-4f99-42ce-8bc7-edb09b2607ea'
```

**Comment by wangzhen-fit2cloud** [comment]
Hi, can you provide the whole pipeline content of your Jenkins job?

**Comment by leopardxu** [comment]
meterSphere environmentId: 'd52aed15-4f99-42ce-8bc7-edb09b2607ea',
            method: 'single', 
            msAccessKey: 'XXXXXXXXXXXXXXXXXXXXX', 
            msEndpoint: 'http://XXXXXXXXXXXX/', 
            msSecretKey: 'XXXXXXXXXXXXXXXXXXXXXX', 
            projectId: '7abf1dc7-4444-4020-9e15-872f4fa1070f', 
            result: 'MeterSphere', 
            testCaseId: '3bc44439-6fa9-4c5a-ac7e-eda4bcb43aa5', 
            testPlanId: '', 
            workspaceId: '5d901b85-21d2-11eb-8bf5-0242ac130003'

**Comment by wangzhen-fit2cloud** [comment]
Thanks a lot, it seems like a bug of our plugin, we'll fix this in our next release.

**Comment by leopardxu** [comment]
please do it as noon as possible and i will try it.

**Comment by xiongxiaoqing614** [comment]
@leopardxu @wangzhen-fit2cloud It's better to use project name, workspace name and test plan name instead of ids. What do you think?

**Comment by wangzhen-fit2cloud** [comment]
Hi, you can use Scripted Pipeline instead of Declarative Pipeline for now to avoid this problem. And we'll fix this issue in the future.

#### Scripted Pipeline example.
```
node {
    stage('Hello') {
        meterSphere environmentId: 'cb0d23b1-5bac-4c26-8223-ed254f26619d', method: 'single', msAccessKey: 'q9xxxHH', msEndpoint: 'https://x.y.com/', msSecretKey: 'xxxg2Ravxm', projectId: '3849c09f-3ae0-4251-bf5e-e07ccb25fd37', result: 'jenkins', testCaseId: '2204e8bf-79ed-48c7-aec3-483d86eee97a', testPlanId: '', workspaceId: '2f4ba241-e636-433a-811c-cf519818601b'
    }
}
```

**Comment by leopardxu** [comment]
i  must using uuid to match projectname or environment. i think using project name will more efficient .  thank you @wangzhen-fit2cloud
