### ISSUE TITLE
希望跑完jenkins结果后，能有个链接，可以链接到metersphere的运行结果

### ISSUE THREAD

**Issue by juewuer** [metersphere/jenkins-plugin#4]
目前跑完，只能去metersphere查看报告，如果报告多，都不知道是哪次

**Comment by wholegale39** [comment]
V1.6.1版本支持查看报告，但是报告链接地址不对，不应该是localhost
[MeterSphere，代码测试]点击链接进入baidu1测试报告页面:http://localhost:8081/#/api/report/view/7deecac6-3ce3-4f4d-908f-068281808043

**Comment by wangzhen-fit2cloud** [comment]
你好，请更新 metersphere 及插件到 1.7.3 版本进行验证。

**Comment by wangzhen-fit2cloud** [comment]
> V1.6.1版本支持查看报告，但是报告链接地址不对，不应该是localhost
> [MeterSphere，代码测试]点击链接进入baidu1测试报告页面:http://localhost:8081/#/api/report/view/7deecac6-3ce3-4f4d-908f-068281808043

你好，该地址引用了 系统-系统设置-当前站点 URL 中的配置，可以修改该配置改为访问 MeterSphere 的地址。
