### ISSUE TITLE
测试计划没读出来呢[LetMeSee]

### ISSUE THREAD

**Issue by G291131988** [metersphere/jenkins-plugin#9]
![image](https://user-images.githubusercontent.com/37016695/104713905-787e8800-575f-11eb-9198-8578146def49.png)
![image](https://user-images.githubusercontent.com/37016695/104713939-816f5980-575f-11eb-8591-9baa27b8c823.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请更新 metersphere 及插件到 1.7.3 版本进行验证。
